name: Murder
main: de.inventivegames.murder.Murder
version: 1.9.6
website: http://www.inventivegames.de
author: inventivetalent
description: >
            Murder-Gamemode Plugin - Copyright inventivetalent 2013-2014!

softdepend: [ProtocolLib]
    
commands:
  Murder:
