name: AntiMinimap
main: de.inventivegames.antiminimap.AntiMinimap
version: 1.0
website: http://www.inventivegames.de
author: inventivetalent
description: >
            AntiMinimap Plugin - Copyright inventivetalent 2014!
