name: Murder
main: de.inventivegames.Murder.Murder
version: 1.7.5
website: http://www.inventivegames.de
author: inventivetalent
description: >
            Murder-Gamemode Plugin - Copyright inventivetalent 2013!

depend: [TagAPI]
loadbefore: [TagAPI]
    
commands:
  Murder:
    description: Murder Command
