name: Murder
main: de.inventivegames.Murder.Murder
version: 1.8.3
website: http://www.inventivegames.de
author: inventivetalent
description: >
            Murder-Gamemode Plugin - Copyright inventivetalent 2013!

softdepend: [TagAPI, ProtocolLib]
    
commands:
  Murder:
